# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_proto.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test_proto.proto',
  package='com.book',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10test_proto.proto\x12\x08\x63om.book\"3\n\x04\x42ook\x12\x0c\n\x04isbn\x18\x01 \x01(\x03\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\"\x1e\n\x0eGetBookRequest\x12\x0c\n\x04isbn\x18\x01 \x01(\x03\"\"\n\x10GetBookViaAuthor\x12\x0e\n\x06\x61uthor\x18\x01 \x01(\t\"v\n\tBookStore\x12\x0c\n\x04name\x18\x01 \x01(\t\x12-\n\x05\x62ooks\x18\x02 \x03(\x0b\x32\x1e.com.book.BookStore.BooksEntry\x1a,\n\nBooksEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*7\n\nEnumSample\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07STARTED\x10\x01\x12\x0b\n\x07RUNNING\x10\x01\x1a\x02\x10\x01\x32\x86\x02\n\x0b\x42ookService\x12\x35\n\x07GetBook\x12\x18.com.book.GetBookRequest\x1a\x0e.com.book.Book\"\x00\x12\x43\n\x11GetBooksViaAuthor\x12\x1a.com.book.GetBookViaAuthor\x1a\x0e.com.book.Book\"\x00\x30\x01\x12?\n\x0fGetGreatestBook\x12\x18.com.book.GetBookRequest\x1a\x0e.com.book.Book\"\x00(\x01\x12:\n\x08GetBooks\x12\x18.com.book.GetBookRequest\x1a\x0e.com.book.Book\"\x00(\x01\x30\x01\x62\x06proto3'
)

_ENUMSAMPLE = _descriptor.EnumDescriptor(
  name='EnumSample',
  full_name='com.book.EnumSample',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STARTED', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RUNNING', index=2, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=b'\020\001',
  serialized_start=271,
  serialized_end=326,
)
_sym_db.RegisterEnumDescriptor(_ENUMSAMPLE)

EnumSample = enum_type_wrapper.EnumTypeWrapper(_ENUMSAMPLE)
UNKNOWN = 0
STARTED = 1
RUNNING = 1



_BOOK = _descriptor.Descriptor(
  name='Book',
  full_name='com.book.Book',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='isbn', full_name='com.book.Book.isbn', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title', full_name='com.book.Book.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='author', full_name='com.book.Book.author', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=81,
)


_GETBOOKREQUEST = _descriptor.Descriptor(
  name='GetBookRequest',
  full_name='com.book.GetBookRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='isbn', full_name='com.book.GetBookRequest.isbn', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=113,
)


_GETBOOKVIAAUTHOR = _descriptor.Descriptor(
  name='GetBookViaAuthor',
  full_name='com.book.GetBookViaAuthor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='author', full_name='com.book.GetBookViaAuthor.author', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=149,
)


_BOOKSTORE_BOOKSENTRY = _descriptor.Descriptor(
  name='BooksEntry',
  full_name='com.book.BookStore.BooksEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='com.book.BookStore.BooksEntry.key', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='com.book.BookStore.BooksEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=269,
)

_BOOKSTORE = _descriptor.Descriptor(
  name='BookStore',
  full_name='com.book.BookStore',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='com.book.BookStore.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='books', full_name='com.book.BookStore.books', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_BOOKSTORE_BOOKSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=269,
)

_BOOKSTORE_BOOKSENTRY.containing_type = _BOOKSTORE
_BOOKSTORE.fields_by_name['books'].message_type = _BOOKSTORE_BOOKSENTRY
DESCRIPTOR.message_types_by_name['Book'] = _BOOK
DESCRIPTOR.message_types_by_name['GetBookRequest'] = _GETBOOKREQUEST
DESCRIPTOR.message_types_by_name['GetBookViaAuthor'] = _GETBOOKVIAAUTHOR
DESCRIPTOR.message_types_by_name['BookStore'] = _BOOKSTORE
DESCRIPTOR.enum_types_by_name['EnumSample'] = _ENUMSAMPLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Book = _reflection.GeneratedProtocolMessageType('Book', (_message.Message,), {
  'DESCRIPTOR' : _BOOK,
  '__module__' : 'test_proto_pb2'
  # @@protoc_insertion_point(class_scope:com.book.Book)
  })
_sym_db.RegisterMessage(Book)

GetBookRequest = _reflection.GeneratedProtocolMessageType('GetBookRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETBOOKREQUEST,
  '__module__' : 'test_proto_pb2'
  # @@protoc_insertion_point(class_scope:com.book.GetBookRequest)
  })
_sym_db.RegisterMessage(GetBookRequest)

GetBookViaAuthor = _reflection.GeneratedProtocolMessageType('GetBookViaAuthor', (_message.Message,), {
  'DESCRIPTOR' : _GETBOOKVIAAUTHOR,
  '__module__' : 'test_proto_pb2'
  # @@protoc_insertion_point(class_scope:com.book.GetBookViaAuthor)
  })
_sym_db.RegisterMessage(GetBookViaAuthor)

BookStore = _reflection.GeneratedProtocolMessageType('BookStore', (_message.Message,), {

  'BooksEntry' : _reflection.GeneratedProtocolMessageType('BooksEntry', (_message.Message,), {
    'DESCRIPTOR' : _BOOKSTORE_BOOKSENTRY,
    '__module__' : 'test_proto_pb2'
    # @@protoc_insertion_point(class_scope:com.book.BookStore.BooksEntry)
    })
  ,
  'DESCRIPTOR' : _BOOKSTORE,
  '__module__' : 'test_proto_pb2'
  # @@protoc_insertion_point(class_scope:com.book.BookStore)
  })
_sym_db.RegisterMessage(BookStore)
_sym_db.RegisterMessage(BookStore.BooksEntry)


_ENUMSAMPLE._options = None
_BOOKSTORE_BOOKSENTRY._options = None

_BOOKSERVICE = _descriptor.ServiceDescriptor(
  name='BookService',
  full_name='com.book.BookService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=329,
  serialized_end=591,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetBook',
    full_name='com.book.BookService.GetBook',
    index=0,
    containing_service=None,
    input_type=_GETBOOKREQUEST,
    output_type=_BOOK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetBooksViaAuthor',
    full_name='com.book.BookService.GetBooksViaAuthor',
    index=1,
    containing_service=None,
    input_type=_GETBOOKVIAAUTHOR,
    output_type=_BOOK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetGreatestBook',
    full_name='com.book.BookService.GetGreatestBook',
    index=2,
    containing_service=None,
    input_type=_GETBOOKREQUEST,
    output_type=_BOOK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetBooks',
    full_name='com.book.BookService.GetBooks',
    index=3,
    containing_service=None,
    input_type=_GETBOOKREQUEST,
    output_type=_BOOK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BOOKSERVICE)

DESCRIPTOR.services_by_name['BookService'] = _BOOKSERVICE

# @@protoc_insertion_point(module_scope)
